### ISSUE TITLE
Create Character Art

### ISSUE THREAD

**Issue by Conmy** [Conmy/boxman#5]
Bart,

Do you want to tackle a player sprite sheet pushing in all the different directions?

Images are 100x100 but this could change. Preferably create in svg and export a png for use now.

**Comment by BartimaeusTY** [comment]
What kind of player are we having? Still the ball with some emphasis that it is moving in a certain direction or is there going to be a different style character?

**Comment by Conmy** [comment]
At this stage we could go wild and have anything. The ball was always just a place holder while I focused on functionality. I'm open to ideas for characters too. The player could be a mouse pushing cheese if we wanted it to be.

**Comment by BartimaeusTY** [comment]
Ok, I'll have a look into a couple different sprites and we can chop & choose from them or whatever. Though the title Boxman should suggest something about the character I reckon?
